name: Build and Push Docker Image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      uses: docker/build-push-action@v2 
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/gha:latest
          ${{ secrets.DOCKER_USERNAME}}/gha:${{ github.run_number }}
